---
- name: Deploy Docker container to target EC2 machines
  hosts: all
  become: yes
  vars:
    docker_image: "rayanelsharkawy/python-app:V01"
    ubuntu_release_codename: "focal" # Adjust this for the correct Ubuntu version
  tasks:
    - name: Update the apt package index
      apt:
        update_cache: yes

    - name: Install required packages for Docker
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
        state: present

    - name: Add Docker GPG key
      shell: |
        curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -

    - name: Add Docker repository
      apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ubuntu_release_codename }} stable"
        state: present

    - name: Install Docker CE
      apt:
        name: docker-ce
        state: present

    - name: Ensure Docker service is running
      service:
        name: docker
        state: started
        enabled: yes

    - name: Add the user to the Docker group
      user:
        name: ubuntu
        group: docker
        append: yes

    - name: Pull the Docker image
      docker_image:
        name: "{{ docker_image }}"
        source: pull

    - name: Run the Docker container
      docker_container:
        name: my-weather-app
        image: "{{ docker_image }}"
        state: started
        ports:
          - "5000:5000"

    - name: Debug message
      debug:
        msg: "Docker container deployed successfully"
